/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.kosso.audioplayerandroid;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
// import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;

import android.app.Activity;

@Kroll.module(name="AudioplayerAndroid", id="com.kosso.audioplayerandroid", propertyAccessors={
		"metadata",
		"time"
})

public class AudioplayerAndroidModule extends KrollModule
{

	private static final String LCAT = "AudioplayerAndroidModule";

	public AudioplayerAndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "onAppCreate");
	}
		
}

